.TH "HW3.1.hpp" 3 "Пн 1 Май 2017" "Домашнее задание №3.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HW3.1.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iterator>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для Домашнее задание №3\&.1 из исходного текста\&.
