.TH "HW3.1.cpp" 3 "Пн 1 Май 2017" "Домашнее задание №3.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HW3.1.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'HW3\&.1\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Функции"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Домашнее задание №3\&.1 из исходного текста\&.
