.TH "Sentence" 3 "Пн 1 Май 2017" "Домашнее задание №3.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sentence \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HW3\&.1\&.h>\fP
.PP
Базовые классы:\fBWord\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBSentence\fP (const \fBSentence\fP &sen)"
.br
.ti -1c
.RI "\fBSentence\fP (string s)"
.br
.ti -1c
.RI "\fBSentence\fP (const char *s)"
.br
.ti -1c
.RI "\fBSentence\fP (\fBWord\fP w)"
.br
.ti -1c
.RI "\fBSentence\fP (vector< string > v)"
.br
.ti -1c
.RI "vector< string > \fBto_str_vec\fP ()"
.br
.ti -1c
.RI "size_t \fBcount\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "size_t \fBcounter\fP"
.br
.in -1c
.SS "Дополнительные унаследованные члены"
.SH "Конструктор(ы)"
.PP 
.SS "Sentence::Sentence (const \fBSentence\fP & sen)\fC [inline]\fP"

.SS "Sentence::Sentence (string s)"

.SS "Sentence::Sentence (const char * s)"

.SS "Sentence::Sentence (\fBWord\fP w)"

.SS "Sentence::Sentence (vector< string > v)"

.SH "Методы"
.PP 
.SS "size_t Sentence::count ()"

.SS "vector< string > Sentence::to_str_vec ()"

.SH "Данные класса"
.PP 
.SS "size_t Sentence::counter\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Домашнее задание №3\&.1 из исходного текста\&.
